// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Assignment04Test
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new FirefoxDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }
    [Test]
    public void insuraneQuote1()
    {
        
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1550, 838);

        
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Poojan");
        driver.FindElement(By.Id("lastName")).SendKeys("Parmar");
        driver.FindElement(By.Id("address")).SendKeys("34 weber");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2A 1X5");
        driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
        driver.FindElement(By.Id("email")).SendKeys("poojan@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("24");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {

            
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$5500"));
        }
    }
    [Test]
    public void insuraneQuote2()
    {

        
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1535, 824);


        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Poojan");
        driver.FindElement(By.Id("lastName")).SendKeys("Parmar");
        driver.FindElement(By.Id("address")).SendKeys("34 weber");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2A 1X5");
        driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
        driver.FindElement(By.Id("email")).SendKeys("poojan@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("4");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
        }
    }
    [Test]
    public void insuraneQuote3()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1535, 824);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Poojan");
        driver.FindElement(By.Id("lastName")).SendKeys("Parmar");
        driver.FindElement(By.Id("address")).SendKeys("34 weber");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2A 1X5");
        driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
        driver.FindElement(By.Id("email")).SendKeys("poojan@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).SendKeys("9");
        driver.FindElement(By.Id("accidents")).SendKeys("2");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$3905"));
        }
    }
    [Test]
    public void insuraneQuote4()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1535, 824);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Poojan");
        driver.FindElement(By.Id("lastName")).SendKeys("Parmar");
        driver.FindElement(By.Id("address")).SendKeys("34 weber");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2A 1X5");
        driver.FindElement(By.Id("phone")).SendKeys("1234567890");
        driver.FindElement(By.Id("email")).SendKeys("poojan@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("27");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.Id("phone-error")).Click();
        driver.FindElement(By.Id("phone-error")).Click();
        {
            var element = driver.FindElement(By.Id("phone-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("phone-error")).Click();
        driver.FindElement(By.Id("phone-error")).Click();
        driver.FindElement(By.Id("phone-error")).Click();
        {
            var element = driver.FindElement(By.Id("phone-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("phone-error")).Click();
        Assert.That(driver.FindElement(By.Id("phone-error")).Text, Is.EqualTo("Phone Number must follow the patterns 111-111-1111 or (111)111-1111"));
    }
    [Test]
    public void insuraneQuote5()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1535, 824);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Poojan");
        driver.FindElement(By.Id("lastName")).SendKeys("Parmar");
        driver.FindElement(By.Id("address")).SendKeys("34 weber");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2A 1X5");
        driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
        driver.FindElement(By.Id("email")).SendKeys("poojan1gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("28");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.Id("email-error")).Click();
        driver.FindElement(By.Id("email-error")).Click();
        {
            var element = driver.FindElement(By.Id("email-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("email-error")).Click();
        driver.FindElement(By.Id("email-error")).Click();
        {
            var element = driver.FindElement(By.Id("email-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("email-error")).Click();
        driver.FindElement(By.Id("email-error")).Click();
        {
            var element = driver.FindElement(By.Id("email-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("email-error")).Click();
        driver.FindElement(By.Id("email-error")).Click();
        {
            var element = driver.FindElement(By.Id("email-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("email-error")).Click();
        driver.FindElement(By.Id("email-error")).Click();
        {
            var element = driver.FindElement(By.Id("email-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("email-error")).Click();
        driver.FindElement(By.Id("email-error")).Click();
        {
            var element = driver.FindElement(By.Id("email-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("email-error")).Click();
        driver.FindElement(By.Id("email-error")).Click();
        {
            var element = driver.FindElement(By.Id("email-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("email-error")).Click();
        driver.FindElement(By.Id("email-error")).Click();
        {
            var element = driver.FindElement(By.Id("email-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("email-error")).Click();
        Assert.That(driver.FindElement(By.Id("email-error")).Text, Is.EqualTo("Must be a valid email address"));
    }
    [Test]
    public void insuraneQuote6()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1535, 824);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Poojan");
        driver.FindElement(By.Id("lastName")).SendKeys("Parmar");
        driver.FindElement(By.Id("address")).SendKeys("34 weber");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("125aaa");
        driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
        driver.FindElement(By.Id("email")).SendKeys("poojan@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).SendKeys("15");
        driver.FindElement(By.Id("accidents")).SendKeys("1");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.Id("postalCode-error")).Click();
        driver.FindElement(By.Id("postalCode-error")).Click();
        {
            var element = driver.FindElement(By.Id("postalCode-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("postalCode-error")).Click();
        Assert.That(driver.FindElement(By.Id("postalCode-error")).Text, Is.EqualTo("Postal Code must follow the pattern A1A 1A1"));
    }
    [Test]
    public void insuraneQuote7()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1535, 824);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Poojan");
        driver.FindElement(By.Id("lastName")).SendKeys("Parmar");
        driver.FindElement(By.Id("address")).SendKeys("34 weber");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2A 1X5");
        driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
        driver.FindElement(By.Id("email")).SendKeys("poojan@gmail.com");
        driver.FindElement(By.Id("experience")).SendKeys("5");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.Id("age-error")).Click();
        driver.FindElement(By.Id("age-error")).Click();
        {
            var element = driver.FindElement(By.Id("age-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("age-error")).Click();
        Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Age (>=16) is required"));
    }
    [Test]
    public void insuraneQuote8()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1535, 824);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Poojan");
        driver.FindElement(By.Id("lastName")).SendKeys("Parmar");
        driver.FindElement(By.Id("address")).SendKeys("34 weber ");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2A 1X5");
        driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
        driver.FindElement(By.Id("email")).SendKeys("poojan@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("38");
        driver.FindElement(By.Id("age")).SendKeys("37");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("8");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.Id("accidents-error")).Click();
        driver.FindElement(By.Id("accidents-error")).Click();
        {
            var element = driver.FindElement(By.Id("accidents-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("accidents-error")).Click();
        Assert.That(driver.FindElement(By.Id("accidents-error")).Text, Is.EqualTo("Number of accidents is required"));
    }
    [Test]
    public void insuraneQuote9()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1535, 824);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Poojan");
        driver.FindElement(By.Id("lastName")).SendKeys("Parmar");
        driver.FindElement(By.Id("address")).SendKeys("34 weber");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2A 1X5");
        driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
        driver.FindElement(By.Id("email")).SendKeys("poojan@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("45");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.Id("experience-error")).Click();
        driver.FindElement(By.Id("experience-error")).Click();
        {
            var element = driver.FindElement(By.Id("experience-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("experience-error")).Click();
        Assert.That(driver.FindElement(By.Id("experience-error")).Text, Is.EqualTo("Years of experience is required"));
    }
    [Test]
    public void insuraneQuote10()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1535, 824);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Poojan");
        driver.FindElement(By.Id("address")).SendKeys("34 weber");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2A 1X5");
        driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
        driver.FindElement(By.Id("email")).SendKeys("poojan@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("45");
        driver.FindElement(By.Id("experience")).SendKeys("45");
        driver.FindElement(By.Id("accidents")).SendKeys("45");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.Id("lastName-error")).Click();
        driver.FindElement(By.Id("lastName-error")).Click();
        {
            var element = driver.FindElement(By.Id("lastName-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("lastName-error")).Click();
        driver.FindElement(By.Id("lastName-error")).Click();
        {
            var element = driver.FindElement(By.Id("lastName-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("lastName-error")).Click();
        driver.FindElement(By.Id("lastName-error")).Click();
        {
            var element = driver.FindElement(By.Id("lastName-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("lastName-error")).Click();
        driver.FindElement(By.Id("lastName-error")).Click();
        {
            var element = driver.FindElement(By.Id("lastName-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("lastName-error")).Click();
        driver.FindElement(By.Id("lastName-error")).Click();
        {
            var element = driver.FindElement(By.Id("lastName-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("lastName-error")).Click();
        Assert.That(driver.FindElement(By.Id("lastName-error")).Text, Is.EqualTo("Last Name is required"));
    }
    [Test]
    public void insuraneQuote11()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1535, 824);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Poojan");
        driver.FindElement(By.Id("lastName")).SendKeys("Parmar");
        driver.FindElement(By.Id("address")).SendKeys("14 weber");
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys("Kitcher");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2A1 1X5");
        driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
        driver.FindElement(By.Id("email")).SendKeys("poojan@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("12");
        driver.FindElement(By.Id("experience")).SendKeys("4");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("N2A1 1X5");
        driver.FindElement(By.Id("age-error")).Click();
        driver.FindElement(By.Id("age-error")).Click();
        {
            var element = driver.FindElement(By.Id("age-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("age-error")).Click();
        Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Please enter a value greater than or equal to 16."));
    }
    [Test]
    public void insuraneQuote12()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1535, 824);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Poojan");
        driver.FindElement(By.Id("lastName")).SendKeys("Parmar");
        driver.FindElement(By.Id("address")).SendKeys("22 weber");
        driver.FindElement(By.Id("city")).SendKeys("Kit");
        driver.FindElement(By.Id("postalCode")).SendKeys("A4X 4P5");
        driver.FindElement(By.Id("phone")).SendKeys("1231231231");
        driver.FindElement(By.Id("email")).SendKeys("poojan@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("45");
        driver.FindElement(By.Id("experience")).SendKeys("12");
        driver.FindElement(By.Id("accidents")).SendKeys("12");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.Id("phone-error")).Click();
        driver.FindElement(By.Id("phone-error")).Click();
        {
            var element = driver.FindElement(By.Id("phone-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("phone-error")).Click();
        Assert.That(driver.FindElement(By.Id("phone-error")).Text, Is.EqualTo("Phone Number must follow the patterns 111-111-1111 or (111)111-1111"));
    }
    [Test]
    public void insuraneQuote13()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1535, 824);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Poojan");
        driver.FindElement(By.Id("lastName")).SendKeys("Parmar");
        driver.FindElement(By.Id("address")).SendKeys("24weber");
        driver.FindElement(By.Id("city")).SendKeys("Brantford");
        driver.FindElement(By.Id("postalCode")).SendKeys("M5A 5X9");
        driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
        driver.FindElement(By.Id("email")).SendKeys("poojan@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("40");
        driver.FindElement(By.Id("experience")).SendKeys("10");
        driver.FindElement(By.Id("accidents")).SendKeys("21");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
        }
    }
    [Test]
    public void insuraneQuote14()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1535, 824);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Poojan");
        driver.FindElement(By.Id("lastName")).SendKeys("Parmar");
        driver.FindElement(By.Id("address")).SendKeys("LA");
        driver.FindElement(By.Id("postalCode")).SendKeys("N2A 1X5");
        driver.FindElement(By.Id("phone")).SendKeys("123-123-1234");
        driver.FindElement(By.CssSelector(".card:nth-child(1) > div:nth-child(2)")).Click();
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("poojan@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("12");
        driver.FindElement(By.Id("experience")).SendKeys("1");
        driver.FindElement(By.Id("accidents")).SendKeys("1");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("50");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.Id("city-error")).Click();
        driver.FindElement(By.Id("city-error")).Click();
        {
            var element = driver.FindElement(By.Id("city-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("city-error")).Click();
        driver.FindElement(By.Id("city-error")).Click();
        driver.FindElement(By.Id("city-error")).Click();
        {
            var element = driver.FindElement(By.Id("city-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("city-error")).Click();
        driver.FindElement(By.Id("city-error")).Click();
        {
            var element = driver.FindElement(By.Id("city-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("city-error")).Click();
        Assert.That(driver.FindElement(By.Id("city-error")).Text, Is.EqualTo("City is required"));
    }
    [Test]
    public void insuraneQuote15()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/getQuote.html");
        driver.Manage().Window.Size = new System.Drawing.Size(1535, 824);
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Poojan");
        driver.FindElement(By.Id("address")).SendKeys("34 weber");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("M5K 5M5");
        driver.FindElement(By.Id("phone")).SendKeys("134-456-7894");
        driver.FindElement(By.Id("email")).SendKeys("poojan@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("40");
        driver.FindElement(By.Id("experience")).SendKeys("2");
        driver.FindElement(By.Id("accidents")).SendKeys("23");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.Id("lastName-error")).Click();
        driver.FindElement(By.Id("lastName-error")).Click();
        {
            var element = driver.FindElement(By.Id("lastName-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("lastName-error")).Click();
        driver.FindElement(By.Id("lastName-error")).Click();
        {
            var element = driver.FindElement(By.Id("lastName-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("lastName-error")).Click();
        Assert.That(driver.FindElement(By.Id("lastName-error")).Text, Is.EqualTo("Last Name is required"));
    }
}
